server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: simpleweb

app:
  name: SimpleWeb
  version: @project.version@
  environment: ${APP_ENVIRONMENT:local}
  build:
    sha: ${APP_BUILD_SHA:dev}
    time: ${APP_BUILD_TIME:unknown}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
